repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: destroyed-symlinks
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
        args: ["--fix=lf"]
